# Site settings
title: 21st digital | mobile and web software development
email: hello@21st.digital
email_fabian: fabian@21st.digital
email_philip: philip@21st.digital
email_andres: andres@21st.digital
email_steffen: steffen@21st.digital
description: > # this means to ignore newlines until "baseurl:"
  Wir sind eine digitale Task-Force im Mobile- und Web-Bereich und entwickeln Software von der einfachen App und Website bis zum komplexen Anwendungssystem.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://21st.digital" # the base hostname & protocol for your site

twitter_username: 21stdigital
github_username:  21stdigital

exclude: [Gemfile, Gemfile.lock, CNAME]

# Build settings
markdown: kramdown

# Collections
collections:
  sections:
  projects:
    output: true
  projectsarchive:
    output: true

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "projectsarchive"
    values:
      sitemap: false      