# Site settings
title: 21st digital
email: hello@21st.digital
email_fabian: fabian@21st.digital
email_philip: philip@21st.digital
email_andres: andres@21st.digital
email_steffen: steffen@21st.digital
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://21st.digital" # the base hostname & protocol for your site

twitter_username: 21stdigital
github_username:  21stdigital

exclude: [Gemfile, Gemfile.lock]

# Build settings
markdown: kramdown

# Collections
collections:
  sections:
  projects:
    output: true
  projectsarchive:
    output: true
