# Site settings
title: 21st digital
email: hello@21stdigital.de
description: ""
baseurl: ""
url: "http://21stdigital.de"
author: 21st digital GmbH

# Build settings
markdown: kramdown
permalink: pretty
